WRAP_CLASS("itk::FastApproxMaskRankImageFilter" POINTER)
  FOREACH(d ${WRAP_ITK_DIMS})
    FOREACH(t ${WRAP_ITK_SCALAR})
      FOREACH(l ${WRAP_ITK_INT})
        WRAP_TEMPLATE("${ITKM_I${t}${d}}${ITKM_I${l}${d}}${ITKM_I${t}${d}}"    "${ITKT_I${t}${d}},${ITKT_I${l}${d}},${ITKT_I${t}${d}}")
      ENDFOREACH(l)
    ENDFOREACH(t)
  ENDFOREACH(d)
END_WRAP_CLASS()
